"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigationbar from "./navbar";
import { usePathname } from "next/navigation";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const navbarDisabled = ["/login", "/register"];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          {!navbarDisabled.includes(pathname) && <Navigationbar />}
          {children}
        </Providers>
      </body>
    </html>
  );
}
