"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navigationbar from "./navbar";
import { usePathname } from "next/navigation";
import { Providers } from "./providers";
import { SessionProvider } from "next-auth/react";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const navbarDisabled = ["/login", "/register"];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en" className="dark" data-theme="black">
      <body className={roboto.className}>
        <SessionProvider>
          <Providers>
            {!navbarDisabled.includes(pathname) && <Navigationbar />}
            {children}
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
